### ISSUE TITLE
CONTRIBUTING.MD is out of sync with Contribution Guidelines page

### ISSUE THREAD

**Issue by RedXanadu** [coreruleset/documentation#69]
New options have been added to `CONTRIBUTING.MD`, e.g. paranoia level tag advice.

We need to make sure everything is up to date and nothing gets lost between the two (the MD file and the documentation page).

**Comment by RedXanadu** [comment]
Note: wait until CRS #2832 is merged.

**Comment by dune73** [comment]
So we are sync again? If yes, please close.
