### ISSUE TITLE
docs: Add link to youtube channel to website

### ISSUE THREAD

**Issue by dune73** [coreruleset/documentation#82]
https://www.youtube.com/@owaspmodsecuritycoreruleset

**Comment by RedXanadu** [comment]
Are we using the documentation repo for tracking website issues? IMO they are different things.

**Comment by RedXanadu** [comment]
FWIW, I've filed all previous website update issues on the CRS repo (still one open there, I think.)

**Comment by dune73** [comment]
You are right. Thanks.

**Comment by dune73** [comment]
-> https://github.com/coreruleset/coreruleset/issues/3164
