### ISSUE TITLE
Verify corectness of template tests

### ISSUE THREAD

**Issue by RedXanadu** [coreruleset/documentation#85]
Every time that I copy-paste one of the agreed 'example tests' from the Contribution Guidelines document, my PR gets errors.

We need to verify that the template "gold standard" tests are correct.

**Link to the test templates:** https://github.com/coreruleset/documentation/blob/main/content/development/contribution_guidelines.md#positive-tests

**Comment by theseion** [comment]
The Accept header thing is probably just because `*` is a special token in YAML.
