### ISSUE TITLE
Change references to ".data" files

### ISSUE THREAD

**Issue by RedXanadu** [coreruleset/documentation#93]
As per: https://github.com/coreruleset/coreruleset/pull/3223/files

.data files are now .ra files.

**Comment by theseion** [comment]
Not all `.data` files though. The ones in the `rules` directory that contain lists for `@pm` and friends should not be changed.

**Comment by dune73** [comment]
Correct. Different type of data files.

**Comment by RedXanadu** [comment]
Closing following merge.
