### ISSUE TITLE
Question: Should the compatible WAF engines page include vendors that package ModSecurity too?

### ISSUE THREAD

**Issue by NickMRamirez** [coreruleset/documentation#94]
The [ENGINE AND INTEGRATION OPTIONS page](https://coreruleset.org/docs/deployment/engine_integration_options/) lists WAF engines that are compatible with the ModSecurity configuration language. Several of our products package a variant of ModSecurity, which we have customized for performance.

Is it appropriate to add our customized ModSecurity WAF module to this page?

Thank you,
Nick Ramirez

**Comment by RedXanadu** [comment]
Hi Nick,

That would be fine. What we currently have listed are the CRS-compatible engines and integrations that we ourselves use as CRS developers, or those of our sponsors/employers, or those of our users and collaborators, or those that approach us / make themselves known to us.

I'm aware that HAProxy has WAF + CRS offerings, both commercial/proprietary and via an open source SPOA.

You can see the kind of description lengths that we have under the "Commercial WAF Appliances" section, and you can see that they're impartial and not vendor advertisements/endorsements :) Would you like to work on a blurb to add on that page?

**Comment by NickMRamirez** [comment]
Great! Yes, I'll work on a description and submit a merge request. Thank you for the quick response.

**Comment by NickMRamirez** [comment]
Thank you @RedXanadu, I have opened a pull request: https://github.com/coreruleset/documentation/pull/96

**Comment by RedXanadu** [comment]
Resolved in #96. Thanks again @NickMRamirez!

Closing issue.
